apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-i1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app-i1
  template:
    metadata:
      labels:
        app: php-app-i1
    spec:
      containers:
      - name: php-container
        image: myphpacr.azurecr.io/php-app-i1:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
