apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-i1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-app
  template:
    metadata:
      labels:
        app: drupal-app
    spec:
      containers:
      - name: php-container
        image: myphpacr.azurecr.io/drupal-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
